version: '3'


services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 81:81
    volumes:
      - ./web/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./web/app:/var/www/html/
    restart: always
    depends_on:
      - java-app
    

  java-app:
    container_name: java-app
    build: ./api
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - postgres

  java-redis:
    container_name: java-redis
    build: ./auth
    ports:
      - 8081:8080
    depends_on:
      - redis

      
  postgres:
    container_name: postgres
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      
      
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./:/data

  
  
